@host = http://localhost:8080

### 1. Todo 생성
POST {{host}}/api/todos
Content-Type: application/json
Accept: application/json

{
  "title": "두번째 할일",
  "startDate": "2025-04-01",
  "endDate": "2025-04-10"
}

> {% client.global.set("todoId", response.body.id); %}

###

### 2. Todo 목록 조회
GET {{host}}/api/todos
Accept: application/json

###

### 3. 생성된 Todo 완료/취소 토글
PATCH {{host}}/api/todos/{{todoId}}/toggle
Accept: application/json

###

### 4. 생성된 Todo 삭제
DELETE {{host}}/api/todos/{{todoId}}
Accept: application/json
